### ISSUE TITLE
visualization won't play on mobile (iPhone 6s)

### ISSUE THREAD

**Issue by alifeinbinary** [michaelbromley/soundcloud-visualizer#6]
Has anyone managed to get visualizations to play on mobile? What parameters should I constrict to make this less CPU intensive?

**Comment by michaelbromley** [comment]
Hi,

The visualization is written with the HTML Canvas 2D apis - these are inherently less efficient than, say using a shader which runs on the GPU. When I wrote this, I had no idea about how to do shaders or real 3D graphics - hence this implementation is rather resource-intensive.

Off the top of my head I can think of a number of things which would probably reduce the CPU load:

1. Reduce the number of hexagons.
2. Remove any transparency effects. In my experience, doing stuff with the alpha channel makes a big difference to CPU load. Of course, this might make the visualization look a bit crap.

I am currently learning shader programming, and maybe one day I will attempt to re-implement this as a shader. But currently I am struggling with drawing simple shapes, so don't hold your breath ;)

**Comment by alifeinbinary** [comment]
Thanks for the quick response! Further to your point, you should check out this interesting project https://github.com/wagerfield/flat-surface-shader . It may chew through the battery but it does work on mobile. I found reading the source code and playing with the demo quite educational.

**Comment by michaelbromley** [comment]
That project looks really cool, thanks for point it out. 

I'll close this issue now, since I have no intention of doing further work on this at this time.
